export interface PluginRegistry {
    registerRootComponent(component)
    registerPopoverUserAttributesComponent(component)
    registerPopoverUserActionsComponent(component)
    registerLeftSidebarHeaderComponent(component)
    registerBottomTeamSidebarComponent(component)
    registerPostMessageAttachmentComponent(component)
    registerLinkTooltipComponent(component)
    registerChannelHeaderButtonAction(icon, action, dropdownText, tooltipText)
    registerChannelIntroButtonAction(icon, action, tooltipText)
    registerCallButtonAction(button, dropdownButton, action)
    registerPostTypeComponent(type, component)
    registerPostCardTypeComponent(type, component)
    registerPostWillRenderEmbedComponent(match, component, toggleable)
    registerMainMenuAction(text, action, mobileIcon)
    registerChannelHeaderMenuAction(text, action)
    registerFileDropdownMenuAction(match, text, action)
    registerUserGuideDropdownMenuAction(text, action)
    registerPostDropdownMenuAction(text, action, filter)
    registerPostDropdownSubMenuAction(text, action, filter)
    registerPostDropdownMenuComponent(component)
    registerFileUploadMethod(icon, action, text)
    registerFilesWillUploadHook(hook)
    unregisterComponent(componentId)
    unregisterPostTypeComponent(componentId)
    registerReducer(reducer)
    registerWebSocketEventHandler(event, handler)
    unregisterWebSocketEventHandler(event)
    registerReconnectHandler(handler)
    unregisterReconnectHandler()
    registerMessageWillBePostedHook(hook)
    registerSlashCommandWillBePostedHook(hook)
    registerMessageWillFormatHook(hook)
    registerFilePreviewComponent(override, component)
    registerTranslations(getTranslationsForLocale)
    registerAdminConsolePlugin(func)
    registerAdminConsoleCustomSetting(key, component)
    unregisterAdminConsolePlugin()
    registerRightHandSidebarComponent(component, title)
    registerNeedsTeamRoute(route, component)
    registerCustomRoute(route, component)
    registerMessageWillBeUpdatedHook(hook)
    registerSidebarChannelLinkLabelComponent(component)
    registerChannelToastComponent(component)
    registerGlobalComponent(component)
    registerAppBarComponent(iconUrl, action, tooltipText)
    registerSiteStatisticsHandler(handler)

    // Add more if needed from https://developers.mattermost.com/extend/plugins/webapp/reference
}
